import React from 'react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  onAccept: () => void;
}

const LegalModal: React.FC<Props> = ({ isOpen, onClose, onAccept }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/80 backdrop-blur-sm transition-opacity"
        onClick={onClose}
      ></div>
      
      {/* Modal Content */}
      <div className="relative bg-dark-card border border-bizflow-500 rounded-2xl max-w-lg w-full p-8 shadow-2xl shadow-bizflow-500/20 transform transition-all animate-fade-in-up">
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-bizflow-500 to-transparent"></div>
        
        <div className="flex flex-col items-center text-center mb-6">
          <div className="w-16 h-16 rounded-full bg-bizflow-900/50 border border-bizflow-500 flex items-center justify-center mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-8 h-8 text-bizflow-400">
              <path fillRule="evenodd" d="M12 1.5a5.25 5.25 0 00-5.25 5.25v3a3 3 0 00-3 3v6.75a3 3 0 003 3h10.5a3 3 0 003-3v-6.75a3 3 0 00-3-3v-3c0-2.9-2.35-5.25-5.25-5.25zm3.75 8.25v-3a3.75 3.75 0 10-7.5 0v3h7.5z" clipRule="evenodd" />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-white mb-2">Initiate Enterprise Deployment</h2>
          <p className="text-gray-400 text-sm">
            This action will generate the legally binding incorporation documents and deployment scripts.
          </p>
        </div>

        <div className="bg-gray-900/50 rounded-lg p-4 mb-6 border border-gray-700 text-left overflow-y-auto max-h-48">
          <h3 className="text-bizflow-400 font-bold text-xs uppercase tracking-wider mb-2">Terms of Origin</h3>
          <p className="text-sm text-gray-300 mb-3">
            By proceeding, you acknowledge the <span className="text-white font-semibold">BizFlow Open Source Commercial License</span>.
          </p>
          <ul className="text-xs text-gray-400 space-y-2 list-disc pl-4">
            <li>
              <strong className="text-white">13% Royalty Stake:</strong> Allocated to the Primary Architect (Soumoditya Das) for all gross revenue generated by this entity.
            </li>
            <li>
              <strong className="text-white">13% Equity Stake:</strong> Non-dilutable equity allocated to the Architect in perpetuity.
            </li>
            <li>
              This agreement is irrevocable upon commercial deployment.
            </li>
          </ul>
        </div>

        <div className="flex flex-col gap-3">
          <button 
            onClick={onAccept}
            className="w-full py-3 px-4 bg-bizflow-600 hover:bg-bizflow-500 text-white font-bold rounded-lg transition-all shadow-lg shadow-bizflow-600/30 flex items-center justify-center gap-2"
          >
            I Consent & Deploy
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-5 h-5">
              <path fillRule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clipRule="evenodd" />
            </svg>
          </button>
          <button 
            onClick={onClose}
            className="w-full py-3 px-4 bg-transparent hover:bg-white/5 text-gray-400 font-medium rounded-lg transition-colors"
          >
            Cancel
          </button>
        </div>
        
        <p className="text-[10px] text-gray-600 text-center mt-4">
          Digital Signature ID: {Math.random().toString(36).substr(2, 9).toUpperCase()}
        </p>
      </div>
    </div>
  );
};

export default LegalModal;