import React, { useState, useRef } from 'react';
import { PitchDeckSlide, Language } from '../types';
import { getLabel } from '../utils/i18n';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

interface Props {
  slides: PitchDeckSlide[];
  language: Language;
}

const SectionPitch: React.FC<Props> = ({ slides, language }) => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const slideRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);

  const handleExportPNG = async () => {
    if (!slideRef.current) return;
    setIsExporting(true);
    try {
      const canvas = await html2canvas(slideRef.current, { scale: 2, backgroundColor: '#111827' });
      const image = canvas.toDataURL("image/png");
      const link = document.createElement("a");
      link.href = image;
      link.download = `Slide_${currentSlide + 1}_${slides[currentSlide].title.replace(/\s+/g, '_')}.png`;
      link.click();
    } catch (err) {
      console.error("Export failed", err);
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportPDF = async () => {
    if (!slideRef.current) return;
    setIsExporting(true);
    try {
      const canvas = await html2canvas(slideRef.current, { scale: 2, backgroundColor: '#111827' });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'landscape',
      });
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save('PitchDeck_Slide.pdf');
    } catch (err) {
      console.error("PDF export failed", err);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="flex flex-col space-y-4">
      <div className="flex justify-end gap-2">
        <button 
          onClick={handleExportPNG}
          disabled={isExporting}
          className="flex items-center gap-2 px-4 py-2 bg-bizflow-900/50 hover:bg-bizflow-800 border border-bizflow-500/30 rounded text-xs font-bold text-bizflow-300 transition-colors"
        >
          {isExporting ? 'Processing...' : getLabel(language, 'exportPng')}
        </button>
        <button 
          onClick={handleExportPDF}
          disabled={isExporting}
          className="flex items-center gap-2 px-4 py-2 bg-purple-900/50 hover:bg-purple-800 border border-purple-500/30 rounded text-xs font-bold text-purple-300 transition-colors"
        >
           {isExporting ? 'Processing...' : getLabel(language, 'exportPdf')}
        </button>
      </div>

      <div 
        ref={slideRef}
        className="flex flex-col h-[600px] bg-gray-900 rounded-xl overflow-hidden border border-gray-700 shadow-2xl relative"
      >
        {/* Slide Viewer */}
        <div className="flex-1 p-12 flex flex-col items-center justify-center text-center bg-gradient-to-br from-gray-900 to-gray-800 relative">
          {/* Logo Watermark */}
          <div className="absolute top-6 left-6 flex items-center gap-2 opacity-30">
             <div className="w-4 h-4 rounded-full bg-bizflow-500"></div>
             <span className="font-bold text-white text-xs tracking-widest">BIZFLOW</span>
          </div>

           <div className="absolute top-6 right-6 text-gray-600 font-mono text-sm">
              {getLabel(language, 'slide')} {currentSlide + 1} / {slides.length}
           </div>
           
           <div className="max-w-3xl animate-fade-in key={currentSlide}">
              <h2 className="text-4xl font-bold text-white mb-8 drop-shadow-lg">{slides[currentSlide].title}</h2>
              <div className="text-xl text-gray-300 leading-relaxed whitespace-pre-line mb-8">
                {slides[currentSlide].content}
              </div>
              <div className="inline-block bg-bizflow-900/50 border border-bizflow-500/30 px-4 py-2 rounded text-sm text-bizflow-300">
                 <span className="font-bold uppercase mr-2 text-xs">{getLabel(language, 'visualCue')}:</span> 
                 {slides[currentSlide].visualCue}
              </div>
           </div>
           
           {/* Footer Watermark */}
           <div className="absolute bottom-6 w-full text-center text-[10px] text-gray-700 font-mono">
              CONFIDENTIAL • GENERATED BY BIZFLOW AUTOCEO
           </div>
        </div>
      </div>

      {/* Navigation */}
      <div className="h-20 bg-dark-card border border-gray-700 rounded-xl flex items-center justify-between px-6">
        <button 
          onClick={() => setCurrentSlide(Math.max(0, currentSlide - 1))}
          disabled={currentSlide === 0}
          className="px-4 py-2 rounded hover:bg-gray-800 disabled:opacity-50 text-white font-medium text-sm uppercase tracking-wide"
        >
          ← {getLabel(language, 'prev')}
        </button>
        
        <div className="flex gap-2 overflow-x-auto px-4 max-w-md">
           {slides.map((_, idx) => (
             <button 
               key={idx}
               onClick={() => setCurrentSlide(idx)}
               className={`w-3 h-3 rounded-full transition-colors ${currentSlide === idx ? 'bg-bizflow-500 scale-125 shadow-[0_0_10px_#14b8a6]' : 'bg-gray-700 hover:bg-gray-600'}`}
             />
           ))}
        </div>

        <button 
          onClick={() => setCurrentSlide(Math.min(slides.length - 1, currentSlide + 1))}
          disabled={currentSlide === slides.length - 1}
          className="px-4 py-2 rounded hover:bg-gray-800 disabled:opacity-50 text-white font-medium text-sm uppercase tracking-wide"
        >
          {getLabel(language, 'next')} →
        </button>
      </div>
    </div>
  );
};

export default SectionPitch;